name: Build RustDesk Windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install LLVM/Clang
        run: choco install llvm --yes

      - name: Setup vcpkg + deps (KISS)
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg.exe integrate install
          C:\vcpkg\vcpkg.exe install `
            libyuv:x64-windows-static `
            libvpx:x64-windows-static `
            openssl:x64-windows-static `
            sdl2:x64-windows-static `
            opus:x64-windows-static `
            libpng:x64-windows-static

      - name: Build (release)
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows-static
          CMAKE_TOOLCHAIN_FILE: C:\vcpkg\scripts\buildsystems\vcpkg.cmake
          RUSTFLAGS: -C target-feature=+crt-static
        run: cargo build --release -vv

      - name: Upload artifacts (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-win
          path: |
            target\release\rustdesk*.exe
            target\release\hbbs*.exe
            target\release\hbbr*.exe
