name: Build RustDesk Windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      CMAKE_TOOLCHAIN_FILE: C:\vcpkg\scripts\buildsystems\vcpkg.cmake

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install LLVM/Clang
        run: choco install llvm --yes

      - name: Setup vcpkg (manifest mode)
        shell: pwsh
        run: |
          if (!(Test-Path 'C:\vcpkg\.git')) {
            git clone https://github.com/microsoft/vcpkg C:\vcpkg
            & 'C:\vcpkg\bootstrap-vcpkg.bat'
          } else {
            Write-Host 'vcpkg já presente em C:\vcpkg'
          }
          & 'C:\vcpkg\vcpkg.exe' integrate install

      - name: vcpkg install (usa vcpkg.json do projeto)
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          if (!(Test-Path '.\vcpkg.json')) { Write-Error 'vcpkg.json não encontrado na raiz do repo'; exit 1 }
          & 'C:\vcpkg\vcpkg.exe' install --triplet x64-windows-static

      - name: Build (release)
        env:
          RUSTFLAGS: -C target-feature=+crt-static
        run: cargo build --release -vv

      - name: Upload artifacts (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-win
          path: target\release\*.exe
